#!/usr/bin/env bash

this=$(dirname $(realpath $0))

ln -vs $this/bashrc $HOME/.bashrc
ln -vs $this/bash_logout $HOME/.bash_logout
ln -vs $this/bash_profile $HOME/.bash_profile
ln -vs $this/profile $HOME/.profile

