#!/usr/bin/env bash

rm -vf ~/.bashrc ~/.bash_profile ~/.bash_logout ~/.profile

ln -vs ~/dotfiles/bash/bashrc ~/.bashrc
ln -vs ~/dotfiles/bash/bash_profile ~/.bash_profile
ln -vs ~/dotfiles/bash/bash_logout ~/.bash_logout

ln -vs ~/dotfiles/profile ~/.profile


