#!/usr/bin/env bash

sshDirectory=~/.ssh
sshDotDirectory=~/dotfiles/ssh
title="$(whoami)@$(hostname)"
gitUsername="$(git config --get user.name)"

[ ! -d $sshDirectory ] && mkdir $sshDirectory
rm -vf $sshDirectory/config
ln -vs $sshDotDirectory/config $sshDirectory

#TODO implement OAuth to avoid retyping password

keys="$(curl -u $gitUsername https://api.github.com/user/keys)"
if echo $keys | grep -q $title; then
    echo Github SSH key found for this user
else
    curl -u $gitUsername\
         --data "{\"title\": \"charon@pluto\", \"key\": \"$(cat ~/.ssh/id_rsa_github.pub)\"}" \
         https://api.github.com/user/keys
fi



