theme = "slick"
icons = "awesome"

[[block]]
block = "custom"
command = "echo 'screenshot'"
on_click = "flameshot"

[[block]]
block = "custom"
command = "echo 'bluetooth'"
on_click = "blueberry"

[[block]]
block = "custom"
command = "echo 'wifi'"
on_click = "cmst"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b}"
format_alt = "{ssid} {signal_strength} {ip} {speed_up;K*b}"
interval = 5

[[block]]
block = "custom"
command = "echo '\uf0ac ' `curl ifconfig.me`" # assumes fontawesome icons
interval = 60

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "hueshift"
step = 50
click_temp = 4500

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d/%Y %I:%M"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
