#!/usr/bin/env bash

source ~/dotfiles/config
stDotDirectory=~/dotfiles/st
stDirectory=$repositories/st

if [ ! -d $stDirectory ]; then
    git clone git://git.suckless.org/st $stDirectory
fi

cp -vf $stDotDirectory/config.h $stDirectory/config.h
cd $stDirectory
echo "Running make in `pwd`"
sudo make clean install

