(load "~/.emacs.d/startup.el")
(load "~/.emacs.d/layout.el")
(load "~/.emacs.d/metapost-mode+.el")
(load "~/.emacs.d/org/org.el")
(load "~/.emacs.d/backup.el")
(load "~/.emacs.d/text.el")
(load "~/.emacs.d/skeleton.el")
(load "~/.emacs.d/keys.el")
(load "~/.emacs.d/remote.el")
(load "~/.emacs.d/buffer.el")

(load "~/.emacs.d/code/cpp.el")
(load "~/.emacs.d/code/latex.el")

(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
