#!/usr/bin/env bash

link=~/.emacs.d
this=~/dotfiles/emacs

emacs_custom="custom.el"
emacs_cask="cask_location.el"
cask_location="/usr/share/cask/cask.el"

[[ ! -x `command -v emacs` ]] && sudo pacman -S emacs

if [[ -L $link && -d $link ]]; then
    echo "Removing link $link"
    unlink $link
elif [ -d $link ]; then
    rm -rvf $link
fi

ln -vs $this $link

if [ ! -f $this/$emacs_custom ]; then
    touch $this/$emacs_custom
    echo "Created empty $emacs_custom"
fi

if [[ ! -x `command -v cask` ]]; then
    if [[ ! -x `command -v yay` ]];
       echo "Running yay setup."
       . ~/dotfiles/yay/setup
    fi
    echo "Installing cask."
    yay -S cask
fi

if [ ! -f $this/$emacs_cask ]; then
    touch $this/$emacs_cask
    echo '(setq cask_location $cask_location)' >> $this/$emacs_cask
    echo "Created $emacs_cask with default cask location."
fi
